* TODO xoe tay 100
* TODO hit dat 20
* TODO giam bot lo lang
  https://beautifulmindvn.com/2015/09/06/9-cach-de-giam-su-lo-lang-ngay-tai-day-va-ngay-bay-gio/

  1 Hãy hít thở sâu.

  “Điều đầu tiên phải làm khi bạn lo lắng là hít thở” Tom Corboy, MFT, người sáng lập, giám đốc điều hành của
  Trung tâm OCD tại Los Angeles, đồng tác giả của cuốn “The Mindfulness Workbook for OCD”, nói.

  Hít thở sâu bằng cơ hoành là phương pháp giảm lo âu hiệu quả vì nó kích hoạt khả năng thư giãn của cơ thể. Nó
  giúp cơ thể chuyển các phản ứng hoạt động ở hệ thần kinh giao cảm thành các phản ứng thư giãn ở hệ thần kinh
  đối giao cảm, Marla W. Deibler, PsyD, bác sĩ tâm lí lâm sàng và giám đốc của The Center for Emotional Health of
  Greater Philadelphia, LLC nói.

  Bà đề nghị luyện tập như sau: “Cố gắng hít vào từ từ khi đếm tới 4, đầu tiên hãy hít đầy bụng và sau đó là ngực,
  cố gắng giữ hơi thở của bạn trong vòng 4 tiếng đếm, sau đó từ từ thở ra cũng trong vòng 4 tiếng đếm và lặp đi lặp
  lại nhiều lần”.

  2 Chấp nhận là bạn đang lo lắng.

  Hãy nhớ rằng “Lo âu chỉ là một loại cảm xúc, nó giống như bất kì loại cảm xúc khác”, phát biểu bởi Deibler, đồng
  thời là tác giả của Psych Central blog “Therapy That Works.” Bằng cách nhắc nhở bản thân rằng lo âu chỉ là một
  phản ứng của cảm xúc, bạn có thể bắt đầu chấp nhận nó, Corboy nói.

  Chấp nhận là điều quan trọng vì cố gắng giảm thiểu một cách thấp nhất hay loại bỏ sự lo âu chỉ làm cho nó nặng
  thêm. Nó chỉ kéo dài thêm ý nghĩ về sự lo lắng của bạn là không thể chịu đựng được.

  Tuy nhiên, việc chấp nhận không có nghĩa là bạn phải thích nó hay cho phép bản thân được quyền đau khổ.

  “Nó chỉ có nghĩa là bạn sẽ được hưởng lợi khi chấp nhận thực tại như nó đang là – vào thời điểm đó, thực tại bao
  gồm lo lắng. Điểm mấu chốt ở đây là cảm giác lo lắng sẽ nhẹ hơn so với những gì chúng ta “lý tưởng hoá” nó lên,
  nhưng nó không phải là không thể chịu đựng được.”

  3 Nhận ra rằng não bạn đang “lừa gạt” bạn

  Bác sĩ thần kinh, Kelli Hyland, M.D, đã chứng kiến làm cách nào để não một người khiến họ cảm thấy rằng họ
  đang chết dần vì đau tim trong khi thật ra, họ chỉ đang bị một cơn hoảng loạn tấn công mà thôi. Bà kể lại rằng bà
  có được kinh nghiệm ấy khi còn là một sinh viên y khoa.

  “Tôi đã thấy người lên cơn đau tim và người bị hoảng loạn mà nhìn nhận nó trên cơ sở y tế thì trông có vẻ giống
  hệt nhau. Bằng một cách khôn ngoan, ân cần và đầy kinh nghiệm, vị bác sĩ tâm thần đã nhẹ nhàng đến bên cạnh
  và bình tĩnh nhắc nhở bệnh nhân của mình rằng ông ta không phải đang chết, mọi thứ sẽ qua đi và chỉ là não ông
  ấy đang giở trò thôi. Điều đó cũng đồng thời trấn an tôi và cả hai chúng tôi đã ở lại cùng bệnh nhân đến khi cơn
  hoảng loạn qua đi.”

  Hiện tại, tiến sĩ Hyland, người sở hữu một phòng khám tư nhân ở Salt Lake City, Utah, đã nói với người bệnh của
  cô ấy điều tương tự. “Điều này giúp loại bỏ sự xấu hổ, cảm giác tội lỗi, áp lực, trách nhiệm phải sửa chữa bản thân
  hay tự phán xét trong khi bản thân đang trong tình trạng cần được chăm sóc hơn bao giờ hết.”

  4 Đặt nghi vấn cho những suy nghĩ của bạn

  “Khi mọi người đang lo lắng, não của họ bắt đầu đầy ấp đủ thể loại ý tưởng kì lạ, rất nhiều trong số chúng cực kì
  không thực tế và không thể xảy ra.” Corboy nói. Và những suy nghĩ đó chỉ làm tăng cao tình trạng lo âu sẵn có của
  bản thân.

  Ví dụ, nói về việc bạn giao bánh cưới. Suy nghĩ như “Chúa ơi, tôi không thể làm được, điều đó sẽ giết tôi mất” có
  lẽ sẽ chạy vụt ngang não bạn.

  Tuy nhiên hãy nhắc nhở bản than bạn, đó chả phải là tai họa lớn lao gì, và trên thực tế, sẽ không ai chết khi giao
  bánh cưới cả, Corboy nói.

  “Vâng, có lẽ bạn lo lắng, và có lẽ bạn thậm chí là nhầm lẫn bánh cưới của bạn. Nhưng điều tội tệ nhất sẽ xảy ra là
  một số người, rất nhiều người trong số họ sẽ không còn được gặp lại bạn, một vài người sẽ chỉ cười khúc khích, và
  rằng ngày mai họ sẽ hoàn toàn quên mất việc ấy.”

  Deibler đồng thời cũng đề nghị bạn tự hỏi bản thân để thách thức suy nghĩ của bạn:

** Những điều lo lắng có phải là thật không? 
** Nó có thật sự có khả năng xảy ra không? 
** Nếu điều tồi tệ nhất xảy ra, vậy điều đó sẽ tệ như thế nào? 
** Mình có thể giải quyết nó không? 
** Mình nên làm gì? 
** Nếu một vài điều xấu xảy ra, những điều ấy có ý nghĩa thế nào với mình? 
** Nó có phải là sự thật hay nó chỉ có vẻ giống vậy? 
** Mình cẩn chuẩn bị những gì để phòng ngừa mọi việc có thể xảy đến? 

*** Sử dụng việc tưởng tượng để bình tĩnh

  Hyland đề nghị luyện tập các suy nghĩ dưới đây thường xuyên, điều sẽ làm mọi thứ trở nên dễ dàng hơn khi bạn lo
  lắng.

  “Tưởng tượng bản thân đang ở bờ sông hoặc bên ngoài một công viên yêu thích, cánh đồng hoặc bãi biển. Ngắm
  nhìn lá cây bay qua con sông hoặc những đám mây trôi qua bầu trời. Sắp xếp cảm xúc của bạn, suy nghĩ về cảm
  giác với những đám mây và những chiếc lá, hãy cứ ngắm nhìn chúng trôi nổi.”

  Điều này khá khác biệt so với những thứ mọi người thường làm. Thông thường, chúng ta sắp xếp cảm xúc, suy
  nghĩ và các cảm giác vật lí bằng khả năng hoặc sự phán xét, ví dụ như tốt và xấu, đúng và sai, Hyland nói. Và
  điều này thường làm phóng đại nỗi lo âu. Hãy nhớ rằng “tất cả đều chỉ là thông tin mà thôi.”

  Gift House by KL. 

  Gift House by KL.

*** Hãy là một người quan sát – đừng phán xét.

  Hyland đưa cho những bệnh nhân mới những tấm thẻ 3×5 với dòng chữ viết phía trên:

  “Luyện tập khả năng quan sát (suy nghĩ, cảm giác, cảm xúc, giác quan và sự phán xét) với lòng trắc ẩn, hoặc là
  không có sự phán xét.

  “Tôi có những bệnh nhân trở lại sau hàng tháng hoặc hàng năm, nói rằng họ vẫn giữ tấm thẻ trên gương hoặc trên
  kính xe của họ, và chúng đã giúp ích cho họ.”

*** Sử dụng khả năng tự nói tích cực

  Lo âu có thể tạo ra rất nhiều cuộc trò chuyện tiêu cực. Hãy tự nói với bản thân “Những câu nói ứng phó tích cực”,
  Deibler nói. Ví dụ, bạn có thể nói “cảm giác lo lắng này thật tệ, nhưng tôi có thể sử dụng những chiến lược để quản
  lí nó.”

*** Tập trung vào hiện tại

  “Khi mà người ta lo lắng, họ thường bị ám ảnh về một vài thứ có thể xảy ra trong tương lai.” Corboy nói. Thay vào
  đó, hãy dừng lại, hít thở sâu và tập trung vào những gì đang xảy ra ngay lúc này, ông ấy nói. Kể cả khi một số thứ
  nghiêm trọng có thể xảy ra, việc tập trung vào hiện tại sẽ cải thiện khả năng quản lí tình huống của bạn, ông thêm
  vào.

*** Tập trung vào những hoạt động có ý nghĩa.

  Khi bạn đang cảm thấy lo âu, nó đồng thời cũng giúp tập trung vào những “hoạt động ý nghĩa, có định hướng tốt”,
  Corboy nói. Ông đề nghị bạn tự hỏi bản thân điều gì bạn muốn làm nếu bạn không bị lo lắng.

  Nếu bạn có ý định đi xem một bộ phim, cứ đi đi. Nếu bạn có ý định giặt giũ, hãy cứ làm.

  “Điều tệ nhất bạn có thể làm khi lo âu là ngồi một chỗ thụ động và ám ảnh về những gì mình đang cảm thấy”. Làm
  những điều cần thiết sẽ dạy cho bạn những bài học chủ chốt, ông nói: ra ngoài sẽ làm cho đầu bạn cảm thấy thoải
  mái hơn; bạn có khả năng sống cuộc đời của riêng mình kể cả khi bạn bị lo âu, và bạn sẽ hoàn thành được mọi
  chuyện.

  “Nói cho cùng, hãy bận bịu với những công việc trong cuộc sống. Đừng cứ ngồi đó và tập trung vào sự lo lắng – sẽ
  chẳng có gì tốt đẹp đến đâu.”
